version: "0.01"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  express:
    build: backend/.
    ports:
      - 5070:5070
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SECRET_JWT=${SECRET_JWT}
      - SECRET_REFRESH_TOKEN=${SECRET_REFRESH_TOKEN}
      - SECRET_COOKIE=${SECRET_COOKIE}
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
  frontend:
    build: frontend/.
    ports:
      - 5071:3000
