version: "0.01"
name: budget-smart

# clean:
#   stage: clean
#   image: docker:latest
#   allow_failure: true
#   script:
#     - docker stop personal-website
#     - docker image prune -f
#     - docker container prune -f

services:
  mongo:
    container_name: budget-smart-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
  express:
    container_name: budget-smart-express
    image: budget-smart-express
    build: backend/.
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SECRET_JWT=${SECRET_JWT}
      - SECRET_REFRESH_TOKEN=${SECRET_REFRESH_TOKEN}
      - SECRET_COOKIE=${SECRET_COOKIE}
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - SESSION_EXPIRY = ${SESSION_EXPIRY}
      - REFRESH_TOKEN_EXPIRY = ${REFRESH_TOKEN_EXPIRY}
    ports:
      - 5070:5070
  frontend:
    container_name: budget-smart-frontend
    image: budget-smart-frontend
    build:
      context: frontend/.
      args:
        NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}
    # environment:
    #   - NEXT_PUBLIC_API_ENDPOINT=http://api.budgetsmart.ca/api
    ports:
      - 5071:3000
