import Head from "next/head";
import { Inter } from "@next/font/google";
import Modal from "components/core/Modal";
import { useModal } from "hooks/useModal";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const { showModal, setShowModal } = useModal();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div
				onClick={(e) => {
					e.preventDefault();
					setShowModal(true);
					console.log("Modal Opened");
				}}>
				test
			</div>
			<div>
				{showModal && (
					<Modal
						closeModal={() => {
							setShowModal(false);
						}}
					/>
				)}
			</div>
		</>
	);
}
