import CategoriesWidget from "components/CategoriesWidget/CategoriesWidget";
import Layout from "components/Layout";
import TransactionsWidget from "components/TransactionsWidget/TransactionsWidget";
import Head from "next/head";
import styled from "styled-components";

import { DndProvider } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";

export default function Sort() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SortWrapper>
				<DndProvider backend={HTML5Backend}>
					<CategoriesWidget />
					<TransactionsWidget />
				</DndProvider>
			</SortWrapper>
		</>
	);
}

const SortWrapper = styled.div`
	display: flex;
	gap: 2rem;
`;
